config/routes.rb
Rails.application.routes.draw do
 
  resources :reports
  resources :visits
  devise_for :users
  resources :empresas
  resources :departments

  root to: 'application#index'

  devise_scope :user do
    get "/login" => "devise/sessions#new"
  end

  
end

app/models/visit.rb
class Visit < ActiveRecord::Base
  belongs_to :department
  belongs_to :user
  belongs_to :empresa
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  before_action :set_visit, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  
  # GET /visits
  # GET /visits.json
  def index
    @visits = Visit.all
  end

  # GET /visits/1
  # GET /visits/1.json
  def show
  end

  # GET /visits/new
  def new
    @visit = Visit.new
  end

  # GET /visits/1/edit
  def edit
  end

  # POST /visits
  # POST /visits.json
  def create
    @visit = Visit.new(visit_params)

    respond_to do |format|
      if @visit.save
        format.html { redirect_to @visit, notice: 'Visit was successfully created.' }
        format.json { render :show, status: :created, location: @visit }
      else
        format.html { render :new }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /visits/1
  # PATCH/PUT /visits/1.json
  def update
    respond_to do |format|
      if @visit.update(visit_params)
        format.html { redirect_to @visit, notice: 'Visit was successfully updated.' }
        format.json { render :show, status: :ok, location: @visit }
      else
        format.html { render :edit }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visits/1
  # DELETE /visits/1.json
  def destroy
    @visit.destroy
    respond_to do |format|
      format.html { redirect_to visits_url, notice: 'Visit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_visit
      @visit = Visit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def visit_params
      params.require(:visit).permit(:name, :rg, :cpf, :department_id, :user_id, :entrada, :saida, :empresa_id)
    end
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/visits/_form.html.erb
<%= form_for(@visit) do |f| %>
  <% if @visit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@visit.errors.count, "error") %> prohibited this visit from being saved:</h2>

      <ul>
      <% @visit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :rg %><br>
    <%= f.number_field :rg %>
  </div>
  <div class="field">
    <%= f.label :cpf %><br>
    <%= f.number_field :cpf %>
  </div>
  <div class="field">
    <%= f.label :department_id %><br>
    <%= f.text_field :department_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :entrada %><br>
    <%= f.datetime_select :entrada %>
  </div>
  <div class="field">
    <%= f.label :saida %><br>
    <%= f.datetime_select :saida %>
  </div>
  <div class="field">
    <%= f.label :empresa_id %><br>
    <%= f.text_field :empresa_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/visits/edit.html.erb
<h1>Editing Visit</h1>

<%= render 'form' %>

<%= link_to 'Show', @visit %> |
<%= link_to 'Back', visits_path %>

app/views/visits/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Visits</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Rg</th>
      <th>Cpf</th>
      <th>Department</th>
      <th>User</th>
      <th>Entrada</th>
      <th>Saida</th>
      <th>Empresa</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @visits.each do |visit| %>
      <tr>
        <td><%= visit.name %></td>
        <td><%= visit.rg %></td>
        <td><%= visit.cpf %></td>
        <td><%= visit.department %></td>
        <td><%= visit.user %></td>
        <td><%= visit.entrada %></td>
        <td><%= visit.saida %></td>
        <td><%= visit.empresa %></td>
        <td><%= link_to 'Show', visit %></td>
        <td><%= link_to 'Edit', edit_visit_path(visit) %></td>
        <td><%= link_to 'Destroy', visit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Visit', new_visit_path %>

app/views/visits/new.html.erb
<h1>New Visit</h1>

<%= render 'form' %>

<%= link_to 'Back', visits_path %>

app/views/visits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @visit.name %>
</p>

<p>
  <strong>Rg:</strong>
  <%= @visit.rg %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= @visit.cpf %>
</p>

<p>
  <strong>Department:</strong>
  <%= @visit.department %>
</p>

<p>
  <strong>User:</strong>
  <%= @visit.user %>
</p>

<p>
  <strong>Entrada:</strong>
  <%= @visit.entrada %>
</p>

<p>
  <strong>Saida:</strong>
  <%= @visit.saida %>
</p>

<p>
  <strong>Empresa:</strong>
  <%= @visit.empresa %>
</p>

<%= link_to 'Edit', edit_visit_path(@visit) %> |
<%= link_to 'Back', visits_path %>