config/routes.rb
Rails.application.routes.draw do
 
  resources :reports
  resources :visits
  devise_for :users
  resources :empresas
  resources :departments

  root to: 'application#index'

  devise_scope :user do
    get "/login" => "devise/sessions#new"
  end

  
end

app/models/empresa.rb
class Empresa < ActiveRecord::Base
end

app/controllers/empresas_controller.rb
class EmpresasController < ApplicationController
  before_action :set_empresa, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  
  # GET /empresas
  # GET /empresas.json
  def index
    @empresas = Empresa.all
  end

  # GET /empresas/1
  # GET /empresas/1.json
  def show
  end

  # GET /empresas/new
  def new
    @empresa = Empresa.new
  end

  # GET /empresas/1/edit
  def edit
  end

  # POST /empresas
  # POST /empresas.json
  def create
    @empresa = Empresa.new(empresa_params)

    respond_to do |format|
      if @empresa.save
        format.html { redirect_to @empresa, notice: 'Empresa was successfully created.' }
        format.json { render :show, status: :created, location: @empresa }
      else
        format.html { render :new }
        format.json { render json: @empresa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /empresas/1
  # PATCH/PUT /empresas/1.json
  def update
    respond_to do |format|
      if @empresa.update(empresa_params)
        format.html { redirect_to @empresa, notice: 'Empresa was successfully updated.' }
        format.json { render :show, status: :ok, location: @empresa }
      else
        format.html { render :edit }
        format.json { render json: @empresa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /empresas/1
  # DELETE /empresas/1.json
  def destroy
    @empresa.destroy
    respond_to do |format|
      format.html { redirect_to empresas_url, notice: 'Empresa was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_empresa
      @empresa = Empresa.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def empresa_params
      params.require(:empresa).permit(:nome, :telefone)
    end
end

app/helpers/empresas_helper.rb
module EmpresasHelper
end

app/views/empresas/_form.html.erb
<%= form_for(@empresa) do |f| %>
  <% if @empresa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@empresa.errors.count, "error") %> prohibited this empresa from being saved:</h2>

      <ul>
      <% @empresa.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :telefone %><br>
    <%= f.text_field :telefone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/empresas/edit.html.erb
<h1>Editing Empresa</h1>

<%= render 'form' %>

<%= link_to 'Show', @empresa %> |
<%= link_to 'Back', empresas_path %>

app/views/empresas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Empresas</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Telefone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @empresas.each do |empresa| %>
      <tr>
        <td><%= empresa.nome %></td>
        <td><%= empresa.telefone %></td>
        <td><%= link_to 'Show', empresa %></td>
        <td><%= link_to 'Edit', edit_empresa_path(empresa) %></td>
        <td><%= link_to 'Destroy', empresa, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Empresa', new_empresa_path%>

app/views/empresas/new.html.erb
<h1>New Empresa</h1>

<%= render 'form' %>

<%= link_to 'Back', empresas_path %>

app/views/empresas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @empresa.nome %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @empresa.telefone %>
</p>

<%= link_to 'Edit', edit_empresa_path(@empresa) %> |
<%= link_to 'Back', empresas_path %>